server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # 不将自己注册到Eureka服务中
    fetch-registry: false  # 不需要检索服务
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false  # 关闭自我保护模式
    eviction-interval-timer-in-ms: 30000  # 清理间隔（单位毫秒，默认是60*1000）