server:
  port: 8080

spring:
  application:
    name: admin-backend
  thymeleaf:
    cache: false  # 开发时关闭缓存
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  # FastDFS访问地址配置
  fdfs:
    web-server-url: http://127.0.0.1:8081/  # FastDFS的Nginx访问地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true